# Safety data configuration
# Column names grouped, with parameters to some
---
data_path: safety_processed.csv
contents:
  IDS:  # nominal (object)
    - var: col_id
      name: COLLECTION_NUMBER
      plan: 100000
  DTS:  # date/time (only 1 column)
    - var: col_date
      name: DONATION_DATE
      format: '%Y-%m-%d'
  CAT:  # stratification (category)
    - var: group
      name: GROUP
  SEV:  # severity flags (bool)
    - var: all_ae  # full AE list in the 1st position
      name: ALL_AE_FL
      margin: 0
      aes:  # all possible adverse events
        - '1.1'
        - '1.2'
        - '1.3'
        - '1.4'
        - '1.5'
        - '1.6'
        - '2.1'
        - '3.1'
        - '3.2'
        - '3.3'
        - '3.4'
        - '3.5'
        - '3.6'
        - '3.7'
        - '4.1'
        - '4.2'
        - '4.3'
        - '5.1'
        - '5.2'
        - '6.1'
        - '6.2'
        - '7.1'
        - '7.2'
        - '7.3'
        - '8.1'
        - '9.1'
        - '10.1'
        - '10.2'
        - '10.3'
        - '10.4'
        - '10.5'
        - '10.6'
    - var: non_hyp
      name: NON_HYP_FL
      margin: 0
      aes:
        - '2.1'
        - '3.1'
        - '3.2'
        - '3.3'
        - '3.4'
        - '3.5'
        - '3.6'
        - '3.7'
        - '4.1'
        - '4.2'
        - '4.3'
        - '5.1'
        - '5.2'
        - '6.1'
        - '6.2'
        - '7.1'
        - '7.2'
        - '7.3'
        - '8.1'
        - '9.1'
        - '10.1'
        - '10.2'
        - '10.3'
        - '10.4'
        - '10.5'
        - '10.6'
    - var: hyp
      name: HYP_FL
      margin: 0
      aes:
        - '1.1'
        - '1.2'
        - '1.3'
        - '1.4'
        - '1.5'
        - '1.6'
    - var: sig_hyp
      name: SIG_HYP_FL
      aes:
        - '1.2'
        - '1.3'
        - '1.4'
        - '1.5'
        - '1.6'
      margin: .15
    - var: only_1.1
      name: ONLY_1.1_FL
      margin: 0
      aes:
        - '1.1'
na_filter: True